version: 2
jobs:
  build_shared:
    working_directory: ~/react-auth-shared
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Set Max Memory
          command: NODE_OPTIONS=--max_old_space_size=4096
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Tests
          command: |
            yarn test
      - run:
          name: Build
          command: |
            yarn build

workflows:
  version: 2
  react_native_workflows:
    jobs:
      - build_shared